// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmfVDU-XXD27dCaUMWTafrJqAQNPM49w',
    appId: '1:102650937155:web:27df9ce60ed3c8b3fef9f6',
    messagingSenderId: '102650937155',
    projectId: 'fifo-mobile-application',
    authDomain: 'fifo-mobile-application.firebaseapp.com',
    databaseURL: 'https://fifo-mobile-application-default-rtdb.firebaseio.com',
    storageBucket: 'fifo-mobile-application.appspot.com',
    measurementId: 'G-W9XPD49YZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSySNiGpIcw69nuM9aUBTi1F5NJbin_XU',
    appId: '1:102650937155:android:72648989ea507fe3fef9f6',
    messagingSenderId: '102650937155',
    projectId: 'fifo-mobile-application',
    databaseURL: 'https://fifo-mobile-application-default-rtdb.firebaseio.com',
    storageBucket: 'fifo-mobile-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8o1uFY-J7qeQfRIo2-rkPDHhgvCCCdig',
    appId: '1:102650937155:ios:b9441647d621d64efef9f6',
    messagingSenderId: '102650937155',
    projectId: 'fifo-mobile-application',
    databaseURL: 'https://fifo-mobile-application-default-rtdb.firebaseio.com',
    storageBucket: 'fifo-mobile-application.appspot.com',
    iosClientId: '102650937155-kqrg8dvdckt7numt1i6b036d77j87ma7.apps.googleusercontent.com',
    iosBundleId: 'com.fifoplus.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8o1uFY-J7qeQfRIo2-rkPDHhgvCCCdig',
    appId: '1:102650937155:ios:1de115b2fe8faf30fef9f6',
    messagingSenderId: '102650937155',
    projectId: 'fifo-mobile-application',
    databaseURL: 'https://fifo-mobile-application-default-rtdb.firebaseio.com',
    storageBucket: 'fifo-mobile-application.appspot.com',
    iosBundleId: 'com.fifoplus.fifoPlus.RunnerTests',
  );
}
